services:
  - type: web
    name: salebazzar
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: Salebazzar
      - key: APP_ENV
        value: production
      - key: RUN_SCAN_ON_STARTUP
        value: "false"
      - key: SCAN_INTERVAL_MINUTES
        value: "1080"
      - key: MIN_DISCOUNT_PERCENT
        value: "50"
      - key: MAX_DEALS_PER_CATEGORY
        value: "2000"
      - key: AMAZON_CREATORS_API_ENABLED
        value: "false"
      - key: AMAZON_CREATORS_API_MARKETPLACE
        value: www.amazon.in
      - key: RAINFOREST_ENABLED
        value: "false"
      - key: RAINFOREST_AMAZON_DOMAIN
        value: amazon.in
      - key: RAINFOREST_DEALS_MAX_PAGE
        value: "1"
      - key: RAINFOREST_API_KEY
        sync: false
      - key: AMAZON_AFFILIATE_TAG
        value: salebazzar02-21
      - key: CONTACT_EMAIL
        value: atulya405@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
